//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Neightborhood_Project5_Team19.MichelleServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MichelleServices.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadImage", ReplyAction="http://tempuri.org/IService1/UploadImageResponse")]
        string UploadImage(string imgBytes, string imgName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadImage", ReplyAction="http://tempuri.org/IService1/UploadImageResponse")]
        System.Threading.Tasks.Task<string> UploadImageAsync(string imgBytes, string imgName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListViolations", ReplyAction="http://tempuri.org/IService1/GetListViolationsResponse")]
        string GetListViolations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListViolations", ReplyAction="http://tempuri.org/IService1/GetListViolationsResponse")]
        System.Threading.Tasks.Task<string> GetListViolationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImageFromFilename", ReplyAction="http://tempuri.org/IService1/GetImageFromFilenameResponse")]
        string GetImageFromFilename(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImageFromFilename", ReplyAction="http://tempuri.org/IService1/GetImageFromFilenameResponse")]
        System.Threading.Tasks.Task<string> GetImageFromFilenameAsync(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostEvent", ReplyAction="http://tempuri.org/IService1/PostEventResponse")]
        string PostEvent(string title, string description, string hostedBy, string contactPhone, System.DateTime eventDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostEvent", ReplyAction="http://tempuri.org/IService1/PostEventResponse")]
        System.Threading.Tasks.Task<string> PostEventAsync(string title, string description, string hostedBy, string contactPhone, System.DateTime eventDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetrieveEvents", ReplyAction="http://tempuri.org/IService1/RetrieveEventsResponse")]
        string RetrieveEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetrieveEvents", ReplyAction="http://tempuri.org/IService1/RetrieveEventsResponse")]
        System.Threading.Tasks.Task<string> RetrieveEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAccount", ReplyAction="http://tempuri.org/IService1/CreateAccountResponse")]
        string CreateAccount(string username, string password, string firstname, string lastname, string address, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAccount", ReplyAction="http://tempuri.org/IService1/CreateAccountResponse")]
        System.Threading.Tasks.Task<string> CreateAccountAsync(string username, string password, string firstname, string lastname, string address, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerifyUser", ReplyAction="http://tempuri.org/IService1/VerifyUserResponse")]
        string VerifyUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerifyUser", ReplyAction="http://tempuri.org/IService1/VerifyUserResponse")]
        System.Threading.Tasks.Task<string> VerifyUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetrieveAccounts", ReplyAction="http://tempuri.org/IService1/RetrieveAccountsResponse")]
        string RetrieveAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetrieveAccounts", ReplyAction="http://tempuri.org/IService1/RetrieveAccountsResponse")]
        System.Threading.Tasks.Task<string> RetrieveAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAddressList", ReplyAction="http://tempuri.org/IService1/SendAddressListResponse")]
        string SendAddressList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAddressList", ReplyAction="http://tempuri.org/IService1/SendAddressListResponse")]
        System.Threading.Tasks.Task<string> SendAddressListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Smart_Neightborhood_Project5_Team19.MichelleServices.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Smart_Neightborhood_Project5_Team19.MichelleServices.IService1>, Smart_Neightborhood_Project5_Team19.MichelleServices.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UploadImage(string imgBytes, string imgName) {
            return base.Channel.UploadImage(imgBytes, imgName);
        }
        
        public System.Threading.Tasks.Task<string> UploadImageAsync(string imgBytes, string imgName) {
            return base.Channel.UploadImageAsync(imgBytes, imgName);
        }
        
        public string GetListViolations() {
            return base.Channel.GetListViolations();
        }
        
        public System.Threading.Tasks.Task<string> GetListViolationsAsync() {
            return base.Channel.GetListViolationsAsync();
        }
        
        public string GetImageFromFilename(string filename) {
            return base.Channel.GetImageFromFilename(filename);
        }
        
        public System.Threading.Tasks.Task<string> GetImageFromFilenameAsync(string filename) {
            return base.Channel.GetImageFromFilenameAsync(filename);
        }
        
        public string PostEvent(string title, string description, string hostedBy, string contactPhone, System.DateTime eventDate) {
            return base.Channel.PostEvent(title, description, hostedBy, contactPhone, eventDate);
        }
        
        public System.Threading.Tasks.Task<string> PostEventAsync(string title, string description, string hostedBy, string contactPhone, System.DateTime eventDate) {
            return base.Channel.PostEventAsync(title, description, hostedBy, contactPhone, eventDate);
        }
        
        public string RetrieveEvents() {
            return base.Channel.RetrieveEvents();
        }
        
        public System.Threading.Tasks.Task<string> RetrieveEventsAsync() {
            return base.Channel.RetrieveEventsAsync();
        }
        
        public string CreateAccount(string username, string password, string firstname, string lastname, string address, string email) {
            return base.Channel.CreateAccount(username, password, firstname, lastname, address, email);
        }
        
        public System.Threading.Tasks.Task<string> CreateAccountAsync(string username, string password, string firstname, string lastname, string address, string email) {
            return base.Channel.CreateAccountAsync(username, password, firstname, lastname, address, email);
        }
        
        public string VerifyUser(string username, string password) {
            return base.Channel.VerifyUser(username, password);
        }
        
        public System.Threading.Tasks.Task<string> VerifyUserAsync(string username, string password) {
            return base.Channel.VerifyUserAsync(username, password);
        }
        
        public string RetrieveAccounts() {
            return base.Channel.RetrieveAccounts();
        }
        
        public System.Threading.Tasks.Task<string> RetrieveAccountsAsync() {
            return base.Channel.RetrieveAccountsAsync();
        }
        
        public string SendAddressList() {
            return base.Channel.SendAddressList();
        }
        
        public System.Threading.Tasks.Task<string> SendAddressListAsync() {
            return base.Channel.SendAddressListAsync();
        }
    }
}
